import Nav from 'components/Nav'
import Results from 'components/Results'
import Head from 'next/head'
import Image from 'next/image'
import { useEffect } from 'react'
import request from 'utils/request'
import Header from '../components/Header'

export default function Home({result}) {
  useEffect(()=>{
    alert("*please turn on your vpn*")
  },[])
  return (
    <div>
      <Head>
        <title>Hulu 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <Nav/>
      <Results result={result} />
    </div>
  )
}

export async function getServerSideProps(context){
  const genre = context.query.genre ;
  const fetchRequest = await fetch(`https://api.themoviedb.org/3${request[genre]?.url || request.trending.url}`)
      .then(resp => resp.json());

  return {
    props :{
      result : fetchRequest.results ,
    }
  }
}
